#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Claude Code の PreToolUse フック（matcher: Bash）。
// 判定は lib/guard-core.cjs が持ち、ここは入出力の変換だけを行う。
//
// 拒否に exit code 2 + stderr を使い、JSON の permissionDecision: deny を使っていない。
// このユーザーのグローバル設定が permissions.defaultMode: "bypassPermissions" のため、
// 権限システム経由の判断が bypass 系モードとどう相互作用するか不確実なため。
// exit code 2 は権限システムとは別経路でツール呼び出し自体を止めるので、モードに依存せず効く。
// また、チェックスクリプトの出力を JSON 外皮に包まず、次の修正アクションへ直結する形で渡せる。

const path = require('node:path');

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
	input += chunk;
});
process.stdin.on('end', () => {
	// 以降どこで失敗しても素通しする（fail-open）。
	// hook が壊れて全ての実行がブロックされる事故のほうが被害が大きい。
	let result;
	try {
		const payload = JSON.parse(input);
		if (payload.tool_name && payload.tool_name !== 'Bash') return;

		const { evaluate } = require(path.join(__dirname, 'lib', 'guard-core.cjs'));
		result = evaluate({
			command: (payload.tool_input && payload.tool_input.command) || '',
			cwd: payload.cwd,
		});
	} catch {
		return; // 何も出力しない = 素通し
	}

	if (result.decision === 'deny') {
		process.stderr.write(`${result.reason}\n`);
		process.exit(2);
	}

	if (result.note) {
		process.stdout.write(`${JSON.stringify({ systemMessage: `[harness] ${result.note}` })}\n`);
	}
	// 通過時は沈黙する。グローバル設定の他フックと並行実行されるため、
	// 余計な出力で解釈が競合しないようにする。
});
