#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Claude Code の SessionStart フック。2つの仕事をする。
//
//   1. 用済みのプランを片付ける（scripts/plan-store.cjs gc）
//   2. using-superpowers スキルの全文をセッションの文脈へ流し込む
//
// 2 が Superpowers の肝。スキルは「description がタスクに合致したときだけ」読まれるので、
// 入口のスキルが載っていないと、他のスキルは置いてあるだけで一度も発動しない。
// 上流（obra/superpowers）も同じことを hooks/session-start でやっている。
// ハーネスはプラグインではなく実体コピーで配るため、同じ働きをするものを自前で持つ。
//
// 上流のスクリプトをそのまま使わないのは、あちらが CLAUDE_PLUGIN_ROOT などの
// 環境変数でプラットフォームを見分ける前提で書かれており、配布された実体コピーでは
// どの分岐にも当てはまらないため。

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

// このファイルは <repo>/.claude/hooks/ に置かれる。
const CLAUDE_DIR = path.resolve(__dirname, '..');
const REPO = path.resolve(CLAUDE_DIR, '..');
const BOOTSTRAP_SKILL = path.join(CLAUDE_DIR, 'skills', 'using-superpowers', 'SKILL.md');
const PLAN_STORE = path.join(REPO, 'scripts', 'plan-store.cjs');

// 配布物のうち、このハーネスがフローの継ぎ目として足しているもの。
// スキル本文（vendor）には書けないので、ここで名指しする。
// 詳しい手順は .claude/rules/development-flow.md にあり、そちらは毎セッション全文が載る。
const HARNESS_BRIDGE = [
	'',
	'## このリポジトリでの追加ルール',
	'',
	'このリポジトリは Issue 駆動です。**writing-plans で計画を書いたら、実装に入る前に',
	'`creating-issues` スキルを使って Issue を作ります。** ブランチは Issue 番号を含む名前でしか',
	'切れません（hook が機械的に止めます）。',
	'',
	'プランの保存先は `plans/` です（writing-plans の既定値より、こちらが優先されます）。',
	'',
	'フロー全体は `.claude/rules/development-flow.md` にあります。',
].join('\n');

function gc() {
	try {
		if (!fs.existsSync(PLAN_STORE)) return;
		execFileSync('node', [PLAN_STORE, 'gc'], { cwd: REPO, stdio: 'ignore', timeout: 10_000 });
	} catch {
		// プランの整理に失敗しても、セッションの開始は妨げない。
	}
}

function bootstrap() {
	let skill;
	try {
		skill = fs.readFileSync(BOOTSTRAP_SKILL, 'utf8');
	} catch {
		// スキルが配られていない（excludeShared で外した等）。何も流し込まない。
		return null;
	}

	return [
		'<EXTREMELY_IMPORTANT>',
		'You have superpowers.',
		'',
		"**Below is the full content of your 'using-superpowers' skill — your introduction to",
		"using skills. For all other skills, use the 'Skill' tool:**",
		'',
		skill,
		HARNESS_BRIDGE,
		'</EXTREMELY_IMPORTANT>',
	].join('\n');
}

function main() {
	gc();

	const context = bootstrap();
	if (!context) return;

	process.stdout.write(
		`${JSON.stringify({
			hookSpecificOutput: {
				hookEventName: 'SessionStart',
				additionalContext: context,
			},
		})}\n`,
	);
}

// 何が起きても素通しする（fail-open）。hook が落ちてセッションが始まらないほうが被害が大きい。
try {
	main();
} catch {
	// 何も出力しない。
}
