#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// 「最終レビューを通した」印を扱う。印は .git の中の JSON に置く（コミットにも .gitignore にも関わらない）。
//
//   node scripts/final-review.cjs mark     今のブランチと HEAD のコミットに印を付ける（AI が使う）
//   node scripts/final-review.cjs check    PR を作ってよいかを判定する（ガードが使う）
//   node scripts/final-review.cjs status   今のブランチ、HEAD、印の状態を表示する
//
// 終了コード:
//   0  よい（mark は記録した）
//   1  だめ（check は印が無い・古い。mark は記録できない状態）
//   2  使い方の誤り
//   3  環境の問題（git リポジトリの外で実行した）
//
// 印は「最終レビューを通し、指摘への対応を終えた」という申告で、レビューそのものの証明ではない。
// 配布物（ハーネスが配る場所）だけの変更には印を求めない。.harness.json の
//   { "checks": { "final-review": false } }
// でこの確認を外せる。
//
// Node で書いてあるのは Windows でも同じに動かすため。git の一覧は -z（NUL 区切り）で受ける。

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const EXIT_OK = 0;
const EXIT_NG = 1;
const EXIT_USAGE = 2;
const EXIT_ENV = 3;

const M_MARKED = (branch, sha) => `最終レビューの印を付けました: ${branch} @ ${sha}`;
const M_PLEDGE = 'この印は「最終レビューを通し、指摘への対応を終えた」という申告です。';
const M_DETACHED = 'ブランチの上で実行してください（HEAD がブランチを指していません）。';
const M_PROTECTED = (branch) => `作業ブランチの上で実行してください（${branch} には印を付けません）。`;
const M_EXEMPT = '配布物だけの変更のため、最終レビューの印は求めません。';
const M_NONE = '最終レビューの印がありません。';
const M_AHEAD = '印を付けた後に、コミットが増えています。';
const M_REWRITTEN = '印を付けた後に、コミットが作り直されています。';
const M_ENV = 'git リポジトリの中で実行してください。';
const M_USAGE = '使い方: node scripts/final-review.cjs <mark|check|status>';
const ACTIONS = [
	'対応:',
	'1. ブランチ全体の最終レビューがまだなら、final-review スキルの手順で通してください',
	'2. 通し終えたら、印を付けてください: node scripts/final-review.cjs mark',
	'3. そのあと、gh pr create を単独のコマンドで実行し直してください',
	'',
	'レビューを通さずに印だけを付けないでください。',
	'印なしで進める必要がある場合は、必ずユーザーに確認し、',
	'許可を得たときだけ SKIP_FINAL_REVIEW=1 を先頭に付けてください。',
].join('\n');

// 作業ブランチではない（印を付けない）ブランチ
const PROTECTED_BRANCHES = ['main', 'master'];

// 増えたコミットの一覧に出す上限
const LOG_LIMIT = 20;

function out(line) {
	process.stdout.write(`${line}\n`);
}

function git(args) {
	return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
}

// NUL 区切りで返す git のサブコマンドを配列にする。失敗したら空。
function gitList(args) {
	try {
		return execFileSync('git', [...args, '-z'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
			maxBuffer: Infinity,
		})
			.split('\0')
			.filter(Boolean);
	} catch {
		return [];
	}
}

function gitOk(args) {
	try {
		execFileSync('git', args, { stdio: 'ignore' });
		return true;
	} catch {
		return false;
	}
}

// ハーネスが配る場所か。プロジェクトの持ち物（.github/workflows/ など）は含めない。
function isHarnessPath(p) {
	return [
		/^\.claude\//,
		/^\.githooks\//,
		/^\.github\/ISSUE_TEMPLATE\/task\.md$/,
		/^\.github\/PULL_REQUEST_TEMPLATE\.md$/,
		/^plans\/\.gitignore$/,
		/^scripts\/(harness-check\.cjs|plan-store\.cjs|final-review\.cjs|\.gitattributes)$/,
	].some((re) => re.test(p));
}

function currentBranch() {
	try {
		return git(['symbolic-ref', '--quiet', '--short', 'HEAD']) || null;
	} catch {
		return null;
	}
}

// 既定ブランチからの分岐点〜HEAD で変わったファイル（削除と、名前を変える前の場所を含む）。
// 基準か分岐点が取れなければ null。
function changedFiles() {
	const baseRef = ['origin/main', 'main', 'origin/master', 'master'].find((ref) =>
		gitOk(['rev-parse', '--verify', '--quiet', ref]),
	);
	if (!baseRef) return null;
	let mergeBase;
	try {
		mergeBase = git(['merge-base', baseRef, 'HEAD']);
	} catch {
		return null;
	}
	if (!mergeBase) return null;
	return gitList(['diff', '--name-only', '--no-renames', mergeBase, 'HEAD']);
}

// git の共通ディレクトリ（worktree でも同じ場所）の下に置く。
function storePath() {
	const common = path.resolve(process.cwd(), git(['rev-parse', '--git-common-dir']));
	return path.join(common, 'tk-harness', 'final-review.json');
}

// 読めない・壊れている・形式が違うときは、印が無いものとして扱う。
function readMarks() {
	try {
		const data = JSON.parse(fs.readFileSync(storePath(), 'utf8'));
		if (data && data.version === 1 && data.marks && typeof data.marks === 'object' && !Array.isArray(data.marks)) {
			return data.marks;
		}
	} catch {
		// 読めない・JSON でない
	}
	return {};
}

// 一時ファイルに書いてから置き換える。書きかけのファイルを読ませない。
function writeMarks(marks) {
	const file = storePath();
	fs.mkdirSync(path.dirname(file), { recursive: true });
	const tmp = path.join(path.dirname(file), `final-review.json.${process.pid}.tmp`);
	fs.writeFileSync(tmp, `${JSON.stringify({ version: 1, marks }, null, 2)}\n`);
	fs.renameSync(tmp, file);
}

function head() {
	return git(['rev-parse', 'HEAD']);
}

function short(sha) {
	return sha.slice(0, 7);
}

function cmdMark() {
	const branch = currentBranch();
	if (!branch) {
		out(M_DETACHED);
		return EXIT_NG;
	}
	if (PROTECTED_BRANCHES.includes(branch)) {
		out(M_PROTECTED(branch));
		return EXIT_NG;
	}
	const marks = readMarks();
	for (const name of Object.keys(marks)) {
		if (!gitOk(['show-ref', '--verify', '--quiet', `refs/heads/${name}`])) delete marks[name];
	}
	const commit = head();
	marks[branch] = { commit, markedAt: new Date().toISOString() };
	writeMarks(marks);
	out(M_MARKED(branch, short(commit)));
	out(M_PLEDGE);
	return EXIT_OK;
}

// .harness.json の checks と同じ読み方。無い・壊れていれば有効扱い（安全側）。先頭の BOM は落とす。
function checkEnabled() {
	try {
		const data = JSON.parse(fs.readFileSync('.harness.json', 'utf8').replace(/^﻿/, ''));
		if (data && typeof data.checks === 'object' && data.checks) return data.checks['final-review'] !== false;
	} catch {
		// 無い・壊れている
	}
	return true;
}

function cmdCheck() {
	if (!checkEnabled()) return EXIT_OK;

	const branch = currentBranch();
	if (!branch) {
		out(M_DETACHED);
		return EXIT_NG;
	}

	const changed = changedFiles();
	if (changed && changed.length > 0 && changed.every(isHarnessPath)) {
		out(M_EXEMPT);
		return EXIT_OK;
	}

	const sha = head();
	const mark = readMarks()[branch];
	const marked = mark && typeof mark.commit === 'string' ? mark.commit : null;
	if (marked === sha) return EXIT_OK;

	const lines = [];
	if (!marked) {
		lines.push(M_NONE);
	} else if (gitOk(['merge-base', '--is-ancestor', marked, 'HEAD'])) {
		lines.push(M_AHEAD);
	} else {
		lines.push(M_REWRITTEN);
	}
	lines.push(`ブランチ: ${branch}`, `HEAD: ${short(sha)}`);
	if (marked) lines.push(`印: ${short(marked)}`);
	if (marked && lines[0] === M_AHEAD) {
		try {
			const log = git(['log', '--oneline', '-n', String(LOG_LIMIT), `${marked}..HEAD`]);
			if (log) lines.push(...log.split('\n').map((l) => `  ${l}`));
		} catch {
			// 一覧が取れなくても、判定は変わらない
		}
	}
	lines.push('', ACTIONS);
	out(lines.join('\n'));
	return EXIT_NG;
}

function cmdStatus() {
	const branch = currentBranch();
	const sha = head();
	const mark = branch ? readMarks()[branch] : null;
	const marked = mark && typeof mark.commit === 'string' ? mark.commit : null;
	out(`ブランチ: ${branch || '（なし: HEAD がブランチを指していません）'}`);
	out(`HEAD: ${short(sha)}`);
	out(marked ? `印: ${short(marked)}（${mark.markedAt}）` : '印: なし');
	out(`状態: ${marked ? (marked === sha ? 'HEAD と一致' : 'HEAD と不一致') : '印なし'}`);
	return EXIT_OK;
}

// --- 実行 -------------------------------------------------------------------

let root;
try {
	root = git(['rev-parse', '--show-toplevel']);
} catch {
	process.stderr.write(`${M_ENV}\n`);
	process.exit(EXIT_ENV);
}
process.chdir(root);

const commands = { mark: cmdMark, check: cmdCheck, status: cmdStatus };
const command = commands[process.argv[2]];
if (!command) {
	out(M_USAGE);
	process.exitCode = EXIT_USAGE;
} else {
	// process.exit は書き残しを捨てることがあるので、終了コードだけ決めて自然に終える。
	process.exitCode = command();
}
