#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// 全プロジェクト共通の品質チェック。言語・スタックに依存しないものだけを見る。
// プロジェクト固有のチェック（Lint・型チェック・テストなど）は scripts/quality-check.{cjs,sh}
// が担当する。ファイル名で所有権が分かれており、こちらはハーネスが配布・更新する。
//
//   node scripts/harness-check.cjs
//
// 終了コード:
//   0  合格
//   1  品質上の問題を検出（表示された指摘を修正すること）
//   3  環境の問題で実行できない
//
// 検査するもの:
//   conflict-markers  コンフリクトマーカーの残留
//   secrets           秘匿情報の混入
//   branch-name       ブランチ名の規約（Issue 番号を含むか）
//   issue-exists      ブランチ名の Issue が実在するか
//   quality-check     プロジェクトの品質チェック（scripts/quality-check.*）が置いてあるか
//
// 個別のチェックを外したいプロジェクトは、リポジトリ直下の .harness.json に書く:
//   { "checks": { "secrets": false } }
//
// Node で書いてあるのは Windows でも同じに動かすため。bash 版だった頃は、Git Bash の pwd（/c/...）と
// git の出力（C:/...）の形の違いで自己除外が外れていた。git の出力は -z（NUL 区切り）で受ける。
// 空白や日本語を含むファイル名を行で切ると壊れるため。

const { execFileSync, spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const EXIT_FINDINGS = 1;
const EXIT_ENV = 3;

// 作業ブランチの規約。guard-core.cjs の BRANCH_RE と同じ形。
// 片方だけ直すと「作れるのに送れない」ブランチができるので、変えるときは両方を直す。
const BRANCH_RE = /^(feature|fix)\/[0-9]+-[a-z0-9._-]+$/;

// プロジェクトの品質チェックのファイル名（リポジトリのルートからの相対パス）。guard-core.cjs の CHECKS と同じ並び。
// 片方だけ直すと、置いてあるのに無いと言われる／無いのに通る、が起きるので、変えるときは両方を直す。
const QUALITY_CHECK_FILES = ['scripts/quality-check.cjs', 'scripts/quality-check.mjs', 'scripts/quality-check.js', 'scripts/quality-check.sh'];

// 自分自身。検出パターン（秘匿情報の正規表現など）を必然的に含むので検査から外す。
// ファイル名で見るのは、配布先の scripts/ と正本の share/templates/ の両方を、パスの形を比べずに扱うため。
const SELF_NAME = 'harness-check.cjs';

// git grep に一度に渡すファイル数。Windows のコマンドライン長の上限（約 32K 文字）を超えないように分ける。
const GREP_CHUNK = 100;

let findings = 0;

function out(line) {
	process.stdout.write(`${line}\n`);
}

function fail(title, ...lines) {
	findings += 1;
	out(`\n[NG] ${title}`);
	for (const line of lines) out(line);
}

function git(args) {
	return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
}

// NUL 区切りで返す git のサブコマンドを配列にする。失敗したら空。
function gitList(args) {
	try {
		// bash 版に出力の上限は無いので、上限で黙って切り捨てない（超えると秘匿情報を素通しする）。
		return execFileSync('git', [...args, '-z'], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
			maxBuffer: Infinity,
		})
			.split('\0')
			.filter(Boolean);
	} catch {
		return [];
	}
}

function revExists(ref) {
	try {
		git(['rev-parse', '--verify', '--quiet', ref]);
		return true;
	} catch {
		return false;
	}
}

// gh を叩く。'ok' / 'failed' / 'missing'（gh が無い）
function gh(args) {
	const r = spawnSync('gh', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
	if (r.error && r.error.code === 'ENOENT') return 'missing';
	return r.status === 0 ? 'ok' : 'failed';
}

// --- 環境の確認 -------------------------------------------------------------

let root;
try {
	root = git(['rev-parse', '--show-toplevel']);
} catch {
	process.stderr.write('git リポジトリの中で実行してください。\n');
	process.exit(EXIT_ENV);
}
process.chdir(root);

// チェックが無効化されているか。設定ファイルが無い・壊れている場合は「全チェック有効」に倒す（安全側）。
// 先頭の BOM は落とす。Windows のエディタが付けることがあり、JSON.parse が受け付けない。
let checks = {};
try {
	const data = JSON.parse(fs.readFileSync('.harness.json', 'utf8').replace(/^\uFEFF/, ''));
	if (data && typeof data.checks === 'object' && data.checks) checks = data.checks;
} catch {
	checks = {};
}
const enabled = (name) => checks[name] !== false;

// --- 検査対象の決定 ---------------------------------------------------------
//
// 「これから出ていくもの」を見る。既存のコードベース全体を検査すると、
// 過去から残っている指摘で新しい作業が止まってしまう。
//
// 対象は2つの和集合:
//   (a) 既定ブランチからの分岐点〜HEAD で変更されたファイル（コミット済み）
//   (b) 未コミットの変更（ステージ済み・未ステージ・未追跡）
//
// (b) を含めるのは、この検査をコミット前に手で走らせることがあるため。
// コミット済みの差分だけを見ると、作業中に叩いたとき「0 件」と出て素通ししてしまい、
// 「コミット前に確認せよ」という運用と噛み合わない。

const candidates = [];
const hasHead = revExists('HEAD');
const baseRef = ['origin/main', 'main', 'origin/master', 'master'].find((ref) => revExists(ref)) || null;

let mergeBase = null;
if (baseRef && hasHead) {
	try {
		mergeBase = git(['merge-base', baseRef, 'HEAD']);
	} catch {
		mergeBase = null;
	}
}
if (mergeBase) {
	candidates.push(...gitList(['diff', '--name-only', '--diff-filter=d', mergeBase, 'HEAD']));
} else if (hasHead) {
	// 既定ブランチが見つからない（クローン直後など）。追跡ファイル全体に倒す。
	// 取りこぼすより過剰に見るほうが安全。
	out('既定ブランチが見つかりません。追跡ファイル全体を検査します。');
	candidates.push(...gitList(['ls-files']));
}

// 未コミットの変更（ステージ済み・未ステージ・未追跡）
if (hasHead) candidates.push(...gitList(['diff', '--name-only', '--diff-filter=d', 'HEAD']));
candidates.push(...gitList(['ls-files', '--others', '--exclude-standard']));

// 重複を落としつつ、自分自身を検査から外す。
const seen = new Set();
const changed = [];
for (const f of candidates) {
	if (!f || seen.has(f)) continue;
	seen.add(f);
	if (path.posix.basename(f) === SELF_NAME) continue;
	changed.push(f);
}

out(`共通チェック: ${changed.length} ファイルを検査します`);

// 変更ファイルに対して git grep をかける。-I でバイナリを除外し、--untracked で未追跡も対象に入れる。
// 該当なしのとき git grep は 1 を返すので、エラーとは区別する（0 でヒット、それ以外は無視）。
function grepChanged(pattern) {
	const hits = [];
	for (let i = 0; i < changed.length; i += GREP_CHUNK) {
		const chunk = changed.slice(i, i + GREP_CHUNK);
		// bash 版に出力の上限は無いので、上限で黙って切り捨てない（超えると秘匿情報を素通しする）。
		const r = spawnSync('git', ['grep', '-I', '--untracked', '-n', '-E', '-e', pattern, '--', ...chunk], {
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'ignore'],
			maxBuffer: Infinity,
		});
		if (r.status === 0 && r.stdout) hits.push(r.stdout.replace(/\n$/, ''));
	}
	return hits.join('\n');
}

// --- ① コンフリクトマーカーの残留 -------------------------------------------

if (enabled('conflict-markers')) {
	// マーカーの文字列をリテラルで書かず、組み立てて作る。ここに 7 連続の不等号を
	// 直接書くと、このファイル自体がコンフリクトマーカーを含むことになり、
	// エディタや他のツールの検出に引っかかるため。
	//
	// 中央の区切り（等号 7 個）は見ない。Markdown の見出し下線（====）に誤爆するため。
	// 開始と終了の 2 種だけで、残留したコンフリクトは確実に検出できる。
	const hits = grepChanged(`^(${'<'.repeat(7)}|${'>'.repeat(7)}) `);
	if (hits) {
		fail('コンフリクトマーカーが残っています', hits, '', 'マージの解決が終わっていません。該当箇所を直してからコミットし直してください。');
	}
}

// --- ② 秘匿情報の混入 -------------------------------------------------------

if (enabled('secrets')) {
	// (a) ファイル名で判断できるもの
	const secretFiles = changed.filter((f) => {
		if (/\.(example|sample|template|md)$/.test(f)) return false;
		const base = path.posix.basename(f);
		if (base === '.env' || base.startsWith('.env.')) return true;
		if (/\.(pem|p12|pfx|jks|keystore)$/.test(base)) return true;
		return ['id_rsa', 'id_dsa', 'id_ecdsa', 'id_ed25519'].includes(base);
	});
	if (secretFiles.length > 0) {
		fail(
			'秘匿情報を含む可能性のあるファイルが変更に含まれています',
			secretFiles.map((f) => `  ${f}`).join('\n'),
			'',
			'.gitignore に追加し、git rm --cached で追跡から外してください。',
			'既にリモートへ出ている場合は、鍵やトークンの再発行が必要です。',
		);
	}

	// (b) 内容で判断できるもの
	//
	// 「APIキーらしき長い文字列」のような汎用パターンは使わない。誤検知で送信が
	// 止まるほうが害が大きい。形式が確定していて誤検知しないものだけを見る。
	const secretPatterns = [
		'-----BEGIN [A-Z ]*PRIVATE KEY-----',
		'AKIA[0-9A-Z]{16}',
		'gh[pousr]_[A-Za-z0-9]{36}',
		'xox[baprs]-[0-9A-Za-z-]{10,}',
	];
	for (const pattern of secretPatterns) {
		const hits = grepChanged(pattern);
		if (hits) {
			fail(
				'秘匿情報らしき文字列が含まれています',
				hits,
				'',
				'該当箇所を環境変数や設定ファイルへ追い出してください。',
				'既にリモートへ出ている場合は、鍵やトークンの再発行が必要です。',
			);
		}
	}
}

// --- ③ ブランチ名の規約 -----------------------------------------------------

let branch = '';
try {
	branch = git(['rev-parse', '--abbrev-ref', 'HEAD']);
} catch {
	branch = '';
}

if (enabled('branch-name')) {
	// 既定ブランチと detached HEAD は対象外。そもそも送信が別のガードで止まる。
	if (!['main', 'master', 'HEAD', ''].includes(branch) && !BRANCH_RE.test(branch)) {
		fail(
			`ブランチ名が規約に合っていません: ${branch}`,
			'',
			'  feature/<issue番号>-<内容を表す短い英語>',
			'  fix/<issue番号>-<内容を表す短い英語>',
			'',
			'例: feature/12-task-read-api',
			'',
			'Issue 番号を含めるのは、ブランチと Issue の対応を一目で分かるようにするためです。',
			'作業中のブランチ名は git branch -m <新しい名前> で変更できます。',
		);
	}
}

// --- ④ Issue が実在するか ---------------------------------------------------
//
// ブランチ名に番号が入っていても、その Issue が実在するとは限らない。番号を打ち間違えた
// まま作業が進むと、PR の Closes # が無関係な Issue を閉じるか、どこにも紐付かない。
//
// ネットワークを見にいくので、ブランチを切る瞬間ではなく送信の直前に1回だけ確かめる。
// gh が無い・認証されていない・GitHub のリポジトリでない場合は黙って飛ばす。
// **確かめられないことを理由に送信を止めない。**

if (enabled('issue-exists')) {
	const m = /^(?:feature|fix)\/([0-9]+)(?:-|$)/.exec(branch);
	const issueNumber = m ? m[1] : '';

	if (issueNumber) {
		const view = gh(['issue', 'view', issueNumber, '--json', 'number']);
		if (view === 'failed') {
			// 見えないのが「無い」からなのか「見にいけない」からなのかを切り分ける。
			if (gh(['auth', 'status']) === 'ok' && gh(['repo', 'view', '--json', 'name']) === 'ok') {
				fail(
					`Issue #${issueNumber} が見つかりません`,
					'',
					`  ブランチ: ${branch}`,
					'',
					'ブランチ名の番号が間違っているか、Issue がまだ作られていません。',
					'このまま進めると PR の Closes # がどこにも紐付きません。',
					'',
					'対応:',
					'  - 番号の間違いなら git branch -m <正しい名前> で直してください',
					'  - Issue がまだ無いなら creating-issues スキルで作ってください',
				);
			} else {
				out('Issue の実在確認は飛ばしました（gh が使えないか、GitHub のリポジトリではありません）。');
			}
		}
		// view === 'missing'（gh が無い）は黙って飛ばす
	}
}

// --- ⑤ プロジェクトの品質チェックがあるか -----------------------------------
//
// 見るのは、決まった名前のファイルがあるかどうかだけ。中身は見ない（テスト・Lint・型チェックの
// 走らせ方は言語ごとに違い、共通チェックの側からは確かめられない）。置いたスクリプトが通るかは、
// hook が共通チェックの直後に走らせて確かめる。検査対象（これから出ていくファイル）の絞り込みとは
// 関係なく、毎回見る。

if (enabled('quality-check')) {
	if (!QUALITY_CHECK_FILES.some((f) => fs.existsSync(f))) {
		fail(
			'プロジェクトの品質チェックがありません（scripts/quality-check.cjs または .sh）',
			'',
			'テスト・Lint・型チェックは、push のときに hook がこのファイルを走らせて確かめます。',
			'無いと、このリポジトリでは push の前にテストが1回も走りません。',
			'',
			'対応:',
			'  - writing-quality-checks スキルで scripts/quality-check.cjs（または .sh）を作ってください',
			'  - 走らせるものが無いリポジトリなら、ユーザーに確認したうえで、.harness.json に',
			'    { "checks": { "quality-check": false } } と書いて外してください',
		);
	}
}

// --- 結果 -------------------------------------------------------------------

// process.exit は書き残しを捨てる（Linux のパイプは非同期なので、長い出力の末尾が消える）。終了コードだけ決めて自然に終える。
if (findings > 0) {
	out(`\n共通チェック: ${findings} 件の指摘があります。`);
	process.exitCode = EXIT_FINDINGS;
} else {
	out('共通チェック: 指摘はありません。');
}
