#!/bin/bash
# generated by tk-media harness — DO NOT EDIT
# 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
#
# 全プロジェクト共通の品質チェック。言語・スタックに依存しないものだけを見る。
# プロジェクト固有のチェック（Lint・型チェック・テストなど）は scripts/quality-check.sh
# が担当する。ファイル名で所有権が分かれており、こちらはハーネスが配布・更新する。
#
#   bash scripts/harness-check.sh
#
# 終了コード:
#   0  合格
#   1  品質上の問題を検出（表示された指摘を修正すること）
#   3  環境の問題で実行できない
#
# 個別のチェックを外したいプロジェクトは、リポジトリ直下の .harness.json に書く:
#   { "checks": { "secrets": false } }

set -uo pipefail

findings=0

note() { printf '%s\n' "$*"; }
fail() {
	findings=$((findings + 1))
	printf '\n[NG] %s\n' "$1"
	shift
	[ $# -gt 0 ] && printf '%s\n' "$@"
	return 0
}

# --- 環境の確認 -------------------------------------------------------------

if ! repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
	echo "git リポジトリの中で実行してください。" >&2
	exit 3
fi
cd "$repo_root" || exit 3

config=".harness.json"
# チェックが無効化されているか。jq に依存せず、"<name>": false の形だけを見る素朴な判定。
# 設定ファイルが無い・壊れている場合は「全チェック有効」に倒す（安全側）。
enabled() {
	[ -f "$config" ] || return 0
	grep -Eq "\"$1\"[[:space:]]*:[[:space:]]*false" "$config" && return 1
	return 0
}

# --- 検査対象の決定 ---------------------------------------------------------
#
# 「これから出ていくもの」を見る。既存のコードベース全体を検査すると、
# 過去から残っている指摘で新しい作業が止まってしまう。
#
# 対象は2つの和集合:
#   (a) 既定ブランチからの分岐点〜HEAD で変更されたファイル（コミット済み）
#   (b) 未コミットの変更（ステージ済み・未ステージ・未追跡）
#
# (b) を含めるのは、この検査をコミット前に手で走らせることがあるため。
# コミット済みの差分だけを見ると、作業中に叩いたとき「0 件」と出て素通ししてしまい、
# 「コミット前に確認せよ」という運用と噛み合わない。

candidates=()

base_ref=""
for candidate in origin/main main origin/master master; do
	if git rev-parse --verify --quiet "$candidate" >/dev/null 2>&1; then
		base_ref="$candidate"
		break
	fi
done

if [ -n "$base_ref" ] && merge_base="$(git merge-base "$base_ref" HEAD 2>/dev/null)"; then
	mapfile -t committed < <(git diff --name-only --diff-filter=d "$merge_base" HEAD 2>/dev/null)
	candidates+=("${committed[@]}")
elif git rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
	# 既定ブランチが見つからない（クローン直後など）。追跡ファイル全体に倒す。
	# 取りこぼすより過剰に見るほうが安全。
	note "既定ブランチが見つかりません。追跡ファイル全体を検査します。"
	mapfile -t tracked < <(git ls-files)
	candidates+=("${tracked[@]}")
fi

# 未コミットの変更（ステージ済み・未ステージ・未追跡）
if git rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
	mapfile -t dirty < <(git diff --name-only --diff-filter=d HEAD 2>/dev/null)
	candidates+=("${dirty[@]}")
fi
mapfile -t untracked < <(git ls-files --others --exclude-standard)
candidates+=("${untracked[@]}")

# 重複を落としつつ、このスクリプト自身を検査から外す。検出パターン（コンフリクト
# マーカーや秘匿情報の正規表現）を必然的に含んでおり、自分自身を検出してしまうため。
declare -A seen=()
changed=()
for f in "${candidates[@]}"; do
	[ -n "$f" ] || continue
	[ "$f" = "scripts/harness-check.sh" ] && continue
	[ -n "${seen[$f]:-}" ] && continue
	seen["$f"]=1
	changed+=("$f")
done

echo "共通チェック: ${#changed[@]} ファイルを検査します"

# 変更ファイルに対して git grep をかける。-I でバイナリを除外する。
# --untracked を付けているのは、まだ追跡されていないファイルも検査対象に入るため。
# 該当なしのとき git grep は 1 を返すので、set -e には頼らず戻り値で判定する。
grep_changed() {
	[ ${#changed[@]} -gt 0 ] || return 1
	git grep -I --untracked -n -E -e "$1" -- "${changed[@]}" 2>/dev/null
}

# --- ① コンフリクトマーカーの残留 -------------------------------------------

if enabled "conflict-markers"; then
	# マーカーの文字列をリテラルで書かず、組み立てて作る。ここに 7 連続の不等号を
	# 直接書くと、このファイル自体がコンフリクトマーカーを含むことになり、
	# エディタや他のツールの検出に引っかかるため。
	marker_start="$(printf '<%.0s' $(seq 7))"
	marker_end="$(printf '>%.0s' $(seq 7))"

	# 中央の区切り（等号 7 個）は見ない。Markdown の見出し下線（====）に誤爆するため。
	# 開始と終了の 2 種だけで、残留したコンフリクトは確実に検出できる。
	if hits="$(grep_changed "^(${marker_start}|${marker_end}) ")"; then
		fail "コンフリクトマーカーが残っています" "$hits" \
			"" "マージの解決が終わっていません。該当箇所を直してからコミットし直してください。"
	fi
fi

# --- ② 秘匿情報の混入 -------------------------------------------------------

if enabled "secrets"; then
	# (a) ファイル名で判断できるもの
	secret_files=()
	for f in "${changed[@]}"; do
		case "$f" in
		*.example | *.sample | *.template | *.md) continue ;;
		esac
		case "$(basename "$f")" in
		.env | .env.*) secret_files+=("$f") ;;
		*.pem | *.p12 | *.pfx | *.jks | *.keystore) secret_files+=("$f") ;;
		id_rsa | id_dsa | id_ecdsa | id_ed25519) secret_files+=("$f") ;;
		esac
	done
	if [ ${#secret_files[@]} -gt 0 ]; then
		fail "秘匿情報を含む可能性のあるファイルが変更に含まれています" \
			"$(printf '  %s\n' "${secret_files[@]}")" \
			"" ".gitignore に追加し、git rm --cached で追跡から外してください。" \
			"既にリモートへ出ている場合は、鍵やトークンの再発行が必要です。"
	fi

	# (b) 内容で判断できるもの
	#
	# 「APIキーらしき長い文字列」のような汎用パターンは使わない。誤検知で送信が
	# 止まるほうが害が大きい。形式が確定していて誤検知しないものだけを見る。
	secret_patterns=(
		'-----BEGIN [A-Z ]*PRIVATE KEY-----'
		'AKIA[0-9A-Z]{16}'
		'gh[pousr]_[A-Za-z0-9]{36}'
		'xox[baprs]-[0-9A-Za-z-]{10,}'
	)
	for pattern in "${secret_patterns[@]}"; do
		if hits="$(grep_changed "$pattern")"; then
			fail "秘匿情報らしき文字列が含まれています" "$hits" \
				"" "該当箇所を環境変数や設定ファイルへ追い出してください。" \
				"既にリモートへ出ている場合は、鍵やトークンの再発行が必要です。"
		fi
	done
fi

# --- ③ ブランチ名の規約 -----------------------------------------------------

if enabled "branch-name"; then
	branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')"
	case "$branch" in
	main | master | HEAD | '')
		# 既定ブランチと detached HEAD は対象外。そもそも送信が別のガードで止まる。
		;;
	*)
		if ! printf '%s' "$branch" | grep -Eq '^(feature|fix)/[0-9]+-[a-z0-9._-]+$'; then
			fail "ブランチ名が規約に合っていません: $branch" \
				"" "  feature/<issue番号>-<内容を表す短い英語>" \
				"  fix/<issue番号>-<内容を表す短い英語>" \
				"" "例: feature/12-task-read-api" \
				"" "Issue 番号を含めるのは、ブランチと Issue の対応を一目で分かるようにするためです。" \
				"作業中のブランチ名は git branch -m <新しい名前> で変更できます。"
		fi
		;;
	esac
fi

# --- 結果 -------------------------------------------------------------------

if [ "$findings" -gt 0 ]; then
	printf '\n共通チェック: %d 件の指摘があります。\n' "$findings"
	exit 1
fi

echo "共通チェック: 指摘はありません。"
exit 0
