#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// プランの寿命をブランチに結びつける。
//
//   register <plan-file> [branch]   プランを台帳に載せる
//   link <branch>                   未紐付けのプランを <branch> に紐付ける
//   gc                              紐付いたブランチが消えたプランを消す
//   mirror <src-dir> <since-ms>     外部ディレクトリのプランを取り込む（Cursor 用）
//   status                          台帳の中身を表示する
//
// 消すのは「紐付いたブランチがもう存在しない」プランだけ。
// branch が null のもの（着手前の計画）と、台帳に載っていないファイルには触らない。
// これが「作業が終わるまでプランは残る」の担保になっている。
//
// 全経路 fail-open。台帳が壊れていても、git が使えなくても、プランを巻き添えに消さない。
// hook から呼ばれるため、異常終了して開発を止めるほうが被害が大きい。

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

// ブランチ命名規約。harness-check.sh と同じものを見る。
// これに合わないブランチ（main など）はプランの紐付け対象にしない。
const WORK_BRANCH = /^(feature|fix)\/[0-9]+-/;

const PLANS_DIR = 'plans';
const INDEX_FILE = '.index.json';

function git(args) {
	return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
}

function repoRoot() {
	try {
		return git(['rev-parse', '--show-toplevel']);
	} catch {
		return null;
	}
}

// 生存しているローカルブランチ。取得できなければ null を返す。
// null と空集合を区別するのが重要で、取得に失敗しただけなのに
// 「どのブランチも存在しない」と解釈すると全プランを消してしまう。
function livingBranches() {
	try {
		const out = git(['branch', '--format=%(refname:short)']);
		return new Set(out.split('\n').map((s) => s.trim()).filter(Boolean));
	} catch {
		return null;
	}
}

function plansDir(root) {
	return path.join(root, PLANS_DIR);
}

function indexPath(root) {
	return path.join(plansDir(root), INDEX_FILE);
}

function readIndex(root) {
	try {
		const data = JSON.parse(fs.readFileSync(indexPath(root), 'utf8'));
		if (data && typeof data.plans === 'object' && data.plans) return { version: 1, plans: data.plans };
	} catch {
		// 台帳が無い・壊れている。空として扱う。壊れた台帳を根拠に削除はしない。
	}
	return { version: 1, plans: {} };
}

function writeIndex(root, index) {
	try {
		fs.mkdirSync(plansDir(root), { recursive: true });
		fs.writeFileSync(indexPath(root), `${JSON.stringify(index, null, 2)}\n`);
	} catch {
		// 書けなくても呼び出し元の処理は続行させる。
	}
}

// 台帳のキーは plans/ 直下のファイル名だけにする。
// パスを持たせるとディレクトリ外を指せてしまい、gc が任意のファイルを消しうる。
function planKey(p) {
	const base = path.basename(String(p || '').trim());
	if (!base || base.startsWith('.') || !base.endsWith('.md')) return null;
	return base;
}

function planFiles(root) {
	try {
		return fs
			.readdirSync(plansDir(root), { withFileTypes: true })
			.filter((e) => e.isFile() && !e.name.startsWith('.') && e.name.endsWith('.md'))
			.map((e) => e.name);
	} catch {
		return [];
	}
}

function mtimeMs(root, key) {
	try {
		return fs.statSync(path.join(plansDir(root), key)).mtimeMs;
	} catch {
		return 0;
	}
}

function currentBranch() {
	try {
		const b = git(['rev-parse', '--abbrev-ref', 'HEAD']);
		return b === 'HEAD' ? null : b;
	} catch {
		return null;
	}
}

// ---------------------------------------------------------------- commands

// プランを台帳に載せる。既に載っていれば、未紐付けのときだけブランチを埋める。
// 紐付け済みのものを別のブランチで上書きはしない（先に立った紐付けを正とする）。
function cmdRegister(root, file, branch) {
	const key = planKey(file);
	if (!key) return;
	if (!fs.existsSync(path.join(plansDir(root), key))) return;

	const index = readIndex(root);
	const linked = branch && WORK_BRANCH.test(branch) ? branch : null;
	const prev = index.plans[key];

	if (prev) {
		if (!prev.branch && linked) {
			prev.branch = linked;
			prev.linkedAt = new Date().toISOString();
			writeIndex(root, index);
			process.stdout.write(`[plan-store] ${key} -> ${linked}\n`);
		}
		return;
	}

	index.plans[key] = {
		branch: linked,
		tool: process.env.PLAN_STORE_TOOL || 'claude',
		registeredAt: new Date().toISOString(),
		linkedAt: linked ? new Date().toISOString() : null,
	};
	writeIndex(root, index);
	process.stdout.write(`[plan-store] 登録: ${key}${linked ? ` -> ${linked}` : ''}\n`);
}

// 未紐付けのプランを <branch> に紐付ける。
// 既に紐付いているブランチなら何もしない（冪等。hook とスキルの両方から呼ばれる）。
function cmdLink(root, branch) {
	if (!branch || !WORK_BRANCH.test(branch)) return;

	const index = readIndex(root);
	for (const meta of Object.values(index.plans)) {
		if (meta && meta.branch === branch) return;
	}

	// 台帳にある未紐付けのうち、最後に登録されたもの。
	let best = null;
	let bestAt = -1;
	for (const [key, meta] of Object.entries(index.plans)) {
		if (!meta || meta.branch) continue;
		const at = Date.parse(meta.registeredAt || '') || mtimeMs(root, key);
		if (at > bestAt) {
			best = key;
			bestAt = at;
		}
	}

	// 台帳に候補が無ければ、plans/ の中で最後に触られたファイルへフォールバックする。
	// 登録 hook が効いていない環境（Cursor だけ・hook 未配布）でも紐付けを成立させるため。
	if (!best) {
		for (const key of planFiles(root)) {
			if (index.plans[key]) continue;
			const at = mtimeMs(root, key);
			if (at > bestAt) {
				best = key;
				bestAt = at;
			}
		}
		if (best) index.plans[best] = { branch: null, tool: 'unknown', registeredAt: new Date().toISOString() };
	}

	if (!best) return;

	index.plans[best].branch = branch;
	index.plans[best].linkedAt = new Date().toISOString();
	writeIndex(root, index);
	process.stdout.write(`[plan-store] ${best} -> ${branch}\n`);
}

// 紐付いたブランチがもう無いプランを消す。
function cmdGc(root) {
	const living = livingBranches();
	// ブランチ一覧が取れないときは何もしない。
	// 「全部消えた」と誤解して全プランを削除する事故を防ぐ。
	//
	// 空集合も同じ扱いにする。ブランチが1本も無いのはコミットが1つも無いリポジトリだけで、
	// 正常な状態ではない。取得できたように見えて中身が空、という形で全削除に化けるのを止める。
	if (!living || living.size === 0) return;

	const index = readIndex(root);
	const removed = [];
	let changed = false;

	for (const [key, meta] of Object.entries(index.plans)) {
		const file = path.join(plansDir(root), key);

		// ファイルだけ先に消えている台帳エントリを掃除する。
		if (!fs.existsSync(file)) {
			delete index.plans[key];
			changed = true;
			continue;
		}

		// 未紐付けは対象外。着手前の計画をここで消してはいけない。
		if (!meta || !meta.branch) continue;
		if (living.has(meta.branch)) continue;

		try {
			fs.unlinkSync(file);
			removed.push(`${key} (${meta.branch})`);
		} catch {
			continue; // 消せなかったら台帳も残す。次回また試す。
		}
		delete index.plans[key];
		changed = true;
	}

	if (changed) writeIndex(root, index);
	if (removed.length) process.stdout.write(`[plan-store] 削除: ${removed.join(', ')}\n`);
}

// 外部ディレクトリ（~/.cursor/plans）から、指定時刻より後に触られたプランを取り込む。
// Cursor は保存先を変えられず、プロジェクト横断の共通置き場に書くため、
// mtime による近似でしか「このプロジェクトのプラン」を判定できない。
function cmdMirror(root, srcDir, sinceMs) {
	const since = Number(sinceMs);
	if (!srcDir || !Number.isFinite(since)) return;

	let entries;
	try {
		entries = fs.readdirSync(srcDir, { withFileTypes: true });
	} catch {
		return;
	}

	const index = readIndex(root);
	const branch = currentBranch();
	const linked = branch && WORK_BRANCH.test(branch) ? branch : null;
	const taken = [];
	let changed = false;

	for (const entry of entries) {
		if (!entry.isFile() || !entry.name.endsWith('.md') || entry.name.startsWith('.')) continue;
		const src = path.join(srcDir, entry.name);

		let content;
		try {
			if (fs.statSync(src).mtimeMs <= since) continue;
			content = fs.readFileSync(src);
		} catch {
			continue;
		}

		const dst = path.join(plansDir(root), entry.name);
		try {
			// 同じ内容なら書き戻さない。mtime を動かすと次回の判定が濁る。
			if (fs.existsSync(dst) && fs.readFileSync(dst).equals(content)) continue;
			fs.mkdirSync(plansDir(root), { recursive: true });
			fs.writeFileSync(dst, content);
		} catch {
			continue;
		}

		if (!index.plans[entry.name]) {
			index.plans[entry.name] = {
				branch: linked,
				tool: 'cursor',
				registeredAt: new Date().toISOString(),
				linkedAt: linked ? new Date().toISOString() : null,
			};
			taken.push(entry.name);
			changed = true;
		}
	}

	if (changed) writeIndex(root, index);
	if (taken.length) process.stdout.write(`[plan-store] 取り込み: ${taken.join(', ')}\n`);
}

function cmdStatus(root) {
	const index = readIndex(root);
	const living = livingBranches();
	const keys = Object.keys(index.plans).sort();

	if (keys.length === 0) {
		process.stdout.write('プランはありません。\n');
	}
	for (const key of keys) {
		const meta = index.plans[key] || {};
		const branch = meta.branch || '(未紐付け)';
		let mark = '';
		if (meta.branch && living && !living.has(meta.branch)) mark = '  ← ブランチ消滅。gc で消える';
		process.stdout.write(`  ${key}\n      ${branch}  [${meta.tool || '?'}]${mark}\n`);
	}

	// 台帳に載っていないファイルは gc の対象外。存在だけ知らせる。
	const orphans = planFiles(root).filter((f) => !index.plans[f]);
	if (orphans.length) {
		process.stdout.write(`\n  台帳外（gc では消えません）: ${orphans.join(', ')}\n`);
	}
}

// ---------------------------------------------------------------- main

function main() {
	const [cmd, ...rest] = process.argv.slice(2);
	const root = repoRoot();
	if (!root) return;

	switch (cmd) {
		case 'register':
			cmdRegister(root, rest[0], rest[1] || currentBranch());
			break;
		case 'link':
			cmdLink(root, rest[0] || currentBranch());
			break;
		case 'gc':
			cmdGc(root);
			break;
		case 'mirror':
			cmdMirror(root, rest[0], rest[1]);
			break;
		case 'status':
			cmdStatus(root);
			break;
		default:
			process.stdout.write('usage: plan-store.cjs <register|link|gc|mirror|status> [args]\n');
	}
}

try {
	main();
} catch {
	// fail-open。プランの整理に失敗しても開発は止めない。
}
