#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// プランの寿命をブランチに結びつける。
//
//   register <plan-file> [branch]   プランを台帳に載せる（branch を渡したときだけ紐付ける）
//   link <branch> <plan-file>       指定したプランを <branch> に紐付ける（推測はしない）
//   gc                              紐付いたブランチが消えたプランを消す
//   status                          台帳の中身を表示する
//
// 消すのは「紐付いたブランチがもう存在しない」プランだけ。
// branch が null のもの（着手前の計画）と、台帳に載っていないファイルには触らない。
// これが「作業が終わるまでプランは残る」の担保になっている。
//
// 全経路 fail-open。台帳が壊れていても、git が使えなくても、プランを巻き添えに消さない。
// hook から呼ばれるため、異常終了して開発を止めるほうが被害が大きい。

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

// ブランチ命名規約。harness-check.sh と同じものを見る。
// これに合わないブランチ（main など）はプランの紐付け対象にしない。
const WORK_BRANCH = /^(feature|fix)\/[0-9]+-/;

const PLANS_DIR = 'plans';
const INDEX_FILE = '.index.json';

function git(args) {
	return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
}

function repoRoot() {
	try {
		return git(['rev-parse', '--show-toplevel']);
	} catch {
		return null;
	}
}

// 生存しているローカルブランチ。取得できなければ null を返す。
// null と空集合を区別するのが重要で、取得に失敗しただけなのに
// 「どのブランチも存在しない」と解釈すると全プランを消してしまう。
function livingBranches() {
	try {
		const out = git(['branch', '--format=%(refname:short)']);
		return new Set(out.split('\n').map((s) => s.trim()).filter(Boolean));
	} catch {
		return null;
	}
}

function plansDir(root) {
	return path.join(root, PLANS_DIR);
}

function indexPath(root) {
	return path.join(plansDir(root), INDEX_FILE);
}

function readIndex(root) {
	try {
		const data = JSON.parse(fs.readFileSync(indexPath(root), 'utf8'));
		if (data && typeof data.plans === 'object' && data.plans) return { version: 1, plans: data.plans };
	} catch {
		// 台帳が無い・壊れている。空として扱う。壊れた台帳を根拠に削除はしない。
	}
	return { version: 1, plans: {} };
}

function writeIndex(root, index) {
	try {
		fs.mkdirSync(plansDir(root), { recursive: true });
		fs.writeFileSync(indexPath(root), `${JSON.stringify(index, null, 2)}\n`);
	} catch {
		// 書けなくても呼び出し元の処理は続行させる。
	}
}

// 台帳のキーは plans/ 直下のファイル名だけにする。
// パスを持たせるとディレクトリ外を指せてしまい、gc が任意のファイルを消しうる。
function planKey(p) {
	const base = path.basename(String(p || '').trim());
	if (!base || base.startsWith('.') || !base.endsWith('.md')) return null;
	return base;
}

function planFiles(root) {
	try {
		return fs
			.readdirSync(plansDir(root), { withFileTypes: true })
			.filter((e) => e.isFile() && !e.name.startsWith('.') && e.name.endsWith('.md'))
			.map((e) => e.name);
	} catch {
		return [];
	}
}

// ---------------------------------------------------------------- commands

// プランを台帳に載せる。既に載っていれば、未紐付けのときだけブランチを埋める。
// 紐付け済みのものを別のブランチで上書きはしない（先に立った紐付けを正とする）。
function cmdRegister(root, file, branch) {
	const key = planKey(file);
	if (!key) return;
	if (!fs.existsSync(path.join(plansDir(root), key))) return;

	const index = readIndex(root);
	const linked = branch && WORK_BRANCH.test(branch) ? branch : null;
	const prev = index.plans[key];

	if (prev) {
		if (!prev.branch && linked) {
			prev.branch = linked;
			prev.linkedAt = new Date().toISOString();
			writeIndex(root, index);
			process.stdout.write(`[plan-store] ${key} -> ${linked}\n`);
		}
		return;
	}

	index.plans[key] = {
		branch: linked,
		tool: process.env.PLAN_STORE_TOOL || 'claude',
		registeredAt: new Date().toISOString(),
		linkedAt: linked ? new Date().toISOString() : null,
	};
	writeIndex(root, index);
	process.stdout.write(`[plan-store] 登録: ${key}${linked ? ` -> ${linked}` : ''}\n`);
}

// 指定したプランを <branch> に紐付ける。どのプランかは推測しない。
//
// 以前は「未紐付けのうち最後に登録されたもの」を選んでいた。これだと、プランモードで
// 立てた古いプランが残っていると writing-plans が書いた今回のプラン（台帳に載らない）より
// 古いほうが選ばれ、計画の無い作業のブランチ（取り込み用など）には直前の別の作業の
// プランが紐付いた。どちらも、ブランチを消した時点でそのプランが消える。
// 指定が無ければ何もしない。紐付かないプランは消えないので、残す側に倒れる。
function cmdLink(root, branch, file) {
	if (!branch || !WORK_BRANCH.test(branch)) return;

	const key = planKey(file);
	if (!key) {
		process.stdout.write('[plan-store] 紐付けるプランを指定してください: link <branch> <plan-file>\n');
		return;
	}
	// 探した場所は絶対パスで示す。worktree の中で実行すると、その worktree の plans/ を探してしまう。
	const abs = path.join(plansDir(root), key);
	if (!fs.existsSync(abs)) {
		process.stdout.write(`[plan-store] プランが見つかりません: ${abs}\n`);
		return;
	}

	// 存在しないブランチには紐付けない。ブランチ名を打ち間違えたまま紐付けると、
	// 次の gc で「紐付いたブランチが無い」と判定されてプランが消える。
	const living = livingBranches();
	if (!living || !living.has(branch)) {
		process.stdout.write(`[plan-store] ブランチが見つかりません: ${branch}（先にブランチを切ってから紐付ける）\n`);
		return;
	}

	const index = readIndex(root);
	const prev = index.plans[key];
	if (prev && prev.branch === branch) return; // 冪等
	if (prev && prev.branch) {
		// 先に立った紐付けを正とする。付け替えると、元のブランチの作業中にプランが消えうる。
		process.stdout.write(`[plan-store] ${key} は ${prev.branch} に紐付いています。変更しません\n`);
		return;
	}

	index.plans[key] = {
		branch,
		tool: (prev && prev.tool) || process.env.PLAN_STORE_TOOL || 'claude',
		registeredAt: (prev && prev.registeredAt) || new Date().toISOString(),
		linkedAt: new Date().toISOString(),
	};
	writeIndex(root, index);
	process.stdout.write(`[plan-store] ${key} -> ${branch}\n`);
}

// 紐付いたブランチがもう無いプランを消す。
function cmdGc(root) {
	const living = livingBranches();
	// ブランチ一覧が取れないときは何もしない。
	// 「全部消えた」と誤解して全プランを削除する事故を防ぐ。
	//
	// 空集合も同じ扱いにする。ブランチが1本も無いのはコミットが1つも無いリポジトリだけで、
	// 正常な状態ではない。取得できたように見えて中身が空、という形で全削除に化けるのを止める。
	if (!living || living.size === 0) return;

	const index = readIndex(root);
	const removed = [];
	let changed = false;

	for (const [key, meta] of Object.entries(index.plans)) {
		const file = path.join(plansDir(root), key);

		// ファイルだけ先に消えている台帳エントリを掃除する。
		if (!fs.existsSync(file)) {
			delete index.plans[key];
			changed = true;
			continue;
		}

		// 未紐付けは対象外。着手前の計画をここで消してはいけない。
		if (!meta || !meta.branch) continue;
		if (living.has(meta.branch)) continue;

		try {
			fs.unlinkSync(file);
			removed.push(`${key} (${meta.branch})`);
		} catch {
			continue; // 消せなかったら台帳も残す。次回また試す。
		}
		delete index.plans[key];
		changed = true;
	}

	if (changed) writeIndex(root, index);
	if (removed.length) process.stdout.write(`[plan-store] 削除: ${removed.join(', ')}\n`);
}

function cmdStatus(root) {
	const index = readIndex(root);
	const living = livingBranches();
	const keys = Object.keys(index.plans).sort();

	if (keys.length === 0) {
		process.stdout.write('プランはありません。\n');
	}
	for (const key of keys) {
		const meta = index.plans[key] || {};
		const branch = meta.branch || '(未紐付け)';
		let mark = '';
		if (meta.branch && living && !living.has(meta.branch)) mark = '  ← ブランチ消滅。gc で消える';
		process.stdout.write(`  ${key}\n      ${branch}  [${meta.tool || '?'}]${mark}\n`);
	}

	// 台帳に載っていないファイルは gc の対象外。存在だけ知らせる。
	const orphans = planFiles(root).filter((f) => !index.plans[f]);
	if (orphans.length) {
		process.stdout.write(`\n  台帳外（gc では消えません）: ${orphans.join(', ')}\n`);
	}
}

// ---------------------------------------------------------------- main

function main() {
	const [cmd, ...rest] = process.argv.slice(2);
	const root = repoRoot();
	if (!root) return;

	switch (cmd) {
		case 'register':
			// 今のブランチを勝手に使わない。プランモードはマージ済みの前のブランチの上で走ることもあり、
			// そのブランチに紐付けると、次の作業の手順3でそのブランチを消したときに新しいプランまで消える。
			cmdRegister(root, rest[0], rest[1]);
			break;
		case 'link':
			cmdLink(root, rest[0], rest[1]);
			break;
		case 'gc':
			cmdGc(root);
			break;
		case 'status':
			cmdStatus(root);
			break;
		default:
			process.stdout.write('usage: plan-store.cjs <register|link|gc|status> [args]\n');
	}
}

try {
	main();
} catch {
	// fail-open。プランの整理に失敗しても開発は止めない。
}
