#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Cursor の beforeShellExecution フック。
// 判定は lib/guard-core.cjs が持ち、ここは入出力の変換だけを行う。
// Claude Code 側（claude-guard.cjs）と同じ関数を呼ぶので、両ツールで挙動が揃う。
//
// Cursor は stdout の JSON で判断する:
//   { "permission": "allow" | "deny" | "ask", "user_message": ..., "agent_message": ... }
// user_message はクライアントに、agent_message はモデルに渡る。
// 修正アクションに直結させたいので、拒否理由は両方へ入れる。

const path = require('node:path');

function respond(obj) {
	process.stdout.write(`${JSON.stringify(obj)}\n`);
}

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
	input += chunk;
});
process.stdin.on('end', () => {
	// 以降どこで失敗しても素通しする（fail-open）。
	// hook が壊れて全ての実行がブロックされる事故のほうが被害が大きい。
	// hooks.json 側で failClosed を指定していないので、異常終了しても素通しになる。
	let result;
	try {
		const payload = JSON.parse(input);
		const { evaluate } = require(path.join(__dirname, 'lib', 'guard-core.cjs'));
		result = evaluate({ command: payload.command || '', cwd: payload.cwd });
	} catch {
		respond({ permission: 'allow' });
		return;
	}

	if (result.decision === 'deny') {
		respond({
			permission: 'deny',
			user_message: result.reason,
			agent_message: result.reason,
		});
		return;
	}

	if (result.note) {
		respond({ permission: 'allow', user_message: `[harness] ${result.note}` });
		return;
	}

	respond({ permission: 'allow' });
});
