#!/usr/bin/env node
// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Cursor の sessionStart / stop フック。
//
//   plan-mirror.cjs start   セッション開始時刻を記録し、古いプランを掃除する
//   plan-mirror.cjs stop    このセッション中に書かれたプランを plans/ へ取り込む
//
// どちらのイベントかは引数で渡す。Cursor の入力 JSON のどのキーにイベント名が入るかは
// 保証がないため、hooks.json 側で明示するほうが確実。
//
// Cursor はプランの保存先を変えられず、~/.cursor/plans/ というプロジェクト横断の
// 共通置き場に書く。そのため「このプロジェクトのプラン」はセッション開始時刻との
// 前後関係でしか判定できない。複数プロジェクトを並行して触ると、他プロジェクトの
// プランを拾う可能性がある。拾ったものは未紐付けのまま残り、gc の対象外なので実害は小さい。

const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

// このファイルは <repo>/.cursor/hooks/ に置かれる。
const STORE = path.resolve(__dirname, '..', '..', 'scripts', 'plan-store.cjs');
const CURSOR_PLANS = path.join(os.homedir(), '.cursor', 'plans');
const MARKER = 'plans/.cursor-session';

function store(cwd, args) {
	execFileSync('node', [STORE, ...args], { cwd, stdio: 'ignore' });
}

function onStart(cwd) {
	fs.mkdirSync(path.join(cwd, 'plans'), { recursive: true });
	fs.writeFileSync(path.join(cwd, MARKER), `${Date.now()}\n`);
	store(cwd, ['gc']);
}

function onStop(cwd) {
	let since;
	try {
		since = Number(fs.readFileSync(path.join(cwd, MARKER), 'utf8').trim());
	} catch {
		return; // 開始時刻が無い＝このセッションの範囲が決まらないので取り込まない。
	}
	if (!Number.isFinite(since)) return;
	store(cwd, ['mirror', CURSOR_PLANS, String(since)]);
}

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
	input += chunk;
});
process.stdin.on('end', () => {
	// 以降どこで失敗しても素通しする（fail-open）。
	// hooks.json 側で failClosed を指定していないので、異常終了しても素通しになる。
	try {
		let cwd = process.cwd();
		try {
			const payload = JSON.parse(input);
			if (payload.cwd) cwd = payload.cwd;
		} catch {
			// 入力が読めなくても、Cursor は hook をワークスペースルートで起動するので続行できる。
		}

		if (process.argv[2] === 'start') onStart(cwd);
		else if (process.argv[2] === 'stop') onStop(cwd);
	} catch {
		// 何も出力しない。
	}
});
