// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Issue駆動フローの機械強制。判定ロジックの本体で、hook アダプタから呼ばれる。
//
// 止めるもの:
//   1. Issue 番号を含まない作業ブランチの作成
//   2. main / master 上での git commit・git push
//   3. refspec が main / master を指している git push
//   4. 品質チェックを通っていない git push
//
// 1 が「Issue 駆動」の入口の担保で、4 が出口の担保になっている。
// ブランチを切る時点で Issue 番号を要求するので、Issue を作らずに実装へ入る経路が
// 塞がる。番号が実在するかどうかは push 時に scripts/harness-check.sh が確かめる
// （ネットワークを見にいく判定を、対話の途中に挟まないため）。
//
// 「機械判定できるものはドキュメントに書かない」の方針で、ルール文書に書いた
// フローのうち機械的に判定できる部分をここへ降ろしている。

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

// 保護対象ブランチ。ここへの直接の commit / push を止める。
const PROTECTED_BRANCHES = new Set(['main', 'master']);

// 作業ブランチの規約。scripts/harness-check.sh の branch-name チェックと同じ形。
// 片方だけ直すと「作れるのに送れない」ブランチができるので、変えるときは両方を直す。
const BRANCH_RE = /^(feature|fix)\/[0-9]+-[a-z0-9._-]+$/;

// 品質チェックの2段構え。順序が意味を持つ（安いほうを先に置き、落ちたら次は走らせない）。
const CHECKS = [
	{ script: 'scripts/harness-check.sh', label: '共通チェック' },
	{ script: 'scripts/quality-check.sh', label: 'プロジェクト品質チェック' },
];

// チェックスクリプトの終了コード規約。1 は「品質上の指摘あり」、3 は「環境の問題で
// 実行できない」。後者は直すべき対象が違うので、返す文言を分けている。
const EXIT_ENV_PROBLEM = 3;

// コマンドラインのどこかにある git push / git commit を拾う。
// 素朴な部分一致だと echo で文字列を表示するだけの場合にも誤爆し、逆に
// git -C /path push のようなグローバルオプション付きの形を取りこぼす。以下の正規表現は:
//   - 行頭 or シェル区切り文字（; & | ( ` 改行）の直後に限定する。改行を区切りに含めないと、
//     ヒアドキュメントでコミットした後の行の git push を見落とす
//   - 先頭に環境変数代入（例: FOO=bar git ...）が付いていても許容する
//   - git の直後に -C <path> のようなグローバルオプションが挟まってもよい
//   - git の前にラッパー（rtk など）が挟まってもよい
//   - 最後は push / commit という単語で終わる（pushurl 等への前方一致誤爆を避ける）
// 多少の過検知は許容する。過検知しても「チェックが通れば素通しする」だけで実害が無く、
// 逆に見逃しは仕組みの趣旨に反するため、迷ったら検知する側に倒す。
const GIT_PUSH_RE = /(^|[;&|(`\n])\s*([A-Za-z_][A-Za-z0-9_]*=\S*\s+)*(rtk\s+)?git(\s+-\S+(\s+[^-\s]\S*)?)*\s+push(\s|$)/;
const GIT_COMMIT_RE = /(^|[;&|(`\n])\s*([A-Za-z_][A-Za-z0-9_]*=\S*\s+)*(rtk\s+)?git(\s+-\S+(\s+[^-\s]\S*)?)*\s+commit(\s|$)/;

// ブランチを作るサブコマンドと、新しいブランチ名を取るオプション。`git branch <名前>` は含めない。
// `git branch --merged main` のように「操作対象」と「作成名」を字面で区別できない形が
// あり、誤爆すると後片付けの手順そのものが止まるため。作成経路としては下の3つで足りる
// （取りこぼしても push 時の branch-name チェックで捕まる）。
//
// オプションはサブコマンドごとに見る。同じ -c でも、git の直後なら設定値（git -c key=value）、
// switch の後ならブランチ作成で、意味がまったく違う。
const CREATE_FLAGS = {
	switch: new Set(['-c', '--create', '-C', '--force-create']),
	checkout: new Set(['-b', '-B']),
	worktree: new Set(['-b', '-B']),
};

// git の直後に置けるオプションのうち、値を次の語で取るもの。サブコマンドを探すときに読み飛ばす。
const GLOBAL_OPTS_WITH_VALUE = new Set(['-C', '-c', '--git-dir', '--work-tree', '--namespace', '--config-env']);

// 誤検知やチェック自体の不具合で永久に作業できなくなる事態を避けるための安全弁。
// ユーザーが明示的に許可した場合にのみ使う。AI が自己判断で付けることは
// ルール文書で禁止している（hook 側では「ユーザーの指示か AI の自己判断か」を
// 技術的に区別できないため、そこは文書規約に委ねる）。
const SKIP_QUALITY_RE = /(^|[;&|(`])\s*SKIP_QUALITY_CHECK=1\s/;
const SKIP_BRANCH_RE = /(^|[;&|(`])\s*SKIP_BRANCH_CHECK=1\s/;

function allow() {
	return { decision: 'allow' };
}

function deny(reason) {
	return { decision: 'deny', reason };
}

function git(args, cwd) {
	return execFileSync('git', args, {
		cwd,
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'ignore'],
	}).trim();
}

// push 以降、次のシェル区切り（改行を含む）までの引数を見て、保護ブランチを指す refspec があるか調べる。
// feature/1-main-thing のような名前に誤爆しないよう、ref 全体との一致だけを見る。
// 改行で止めないと、`git push` の次の行の `git switch main` まで引数と読んで誤爆する。
function pushTargetsProtected(command) {
	const m = /\bpush\b([^;&|\n]*)/.exec(command);
	if (!m) return false;
	const args = m[1].trim();
	if (!args) return false;
	for (const token of args.split(/\s+/)) {
		if (token.startsWith('-')) continue;
		// <local>:<remote> の形なら、判定対象は送り先である右辺。
		const ref = token.includes(':') ? token.slice(token.indexOf(':') + 1) : token;
		if (PROTECTED_BRANCHES.has(ref)) return true;
	}
	return false;
}

// ヒアドキュメントの本文を取り除く。本文はコマンドに渡すデータで、実行されない。
// コミットメッセージや PR 本文に書いた git のコマンド例（git switch -c 名前、git push origin main）
// まで呼び出しとして読むと、ブランチ作成や main への送信と取り違えて止めてしまう。
//
// 終わりの行が見つからなければ、ヒアドキュメントではなかった（引用符の中の <<、$((a<<b))、
// cout << x など）とみなし、外した行を戻す。戻して判定しても、止まる側に倒れるだけで済む。
function stripHeredocs(command) {
	const out = [];
	let end = null;
	let dash = false;
	let body = [];
	for (const line of command.split('\n')) {
		if (end !== null) {
			body.push(line);
			// <<- のときだけ、終わりの行の先頭のタブを許す（bash と同じ）。
			if ((dash ? line.replace(/^\t+/, '') : line) === end) {
				end = null;
				body = [];
			}
			continue;
		}
		out.push(line);
		// 終わりの語は 'END-MSG' "EOF" \EOF EOF のどの書き方でもよい。
		// <<< （ヒアストリング）は対象外。直前が < の << は見ない。
		const m = /(?<!<)<<(-?)\s*(?:'([^']+)'|"([^"]+)"|\\?([^\s'"<>|&;()]+))/.exec(line);
		if (m) {
			dash = m[1] === '-';
			end = m[2] || m[3] || m[4];
		}
	}
	if (end !== null) out.push(...body);
	return out.join('\n');
}

// コマンド行を、シェルの区切り（; & | ( ) ` 改行）ごとに切り、git の呼び出しだけを取り出す。
// 最初の git だけを見ると、`git status && git switch -c 名前` の2つ目を見落とし、
// `git init -b main && …` の -b をブランチ作成と取り違える。
// 引用符の中の区切りも切ってしまうが、過検知の側に倒れるだけなので許容する。
function gitInvocations(command) {
	const out = [];
	for (const segment of command.split(/[;&|()`\n]/)) {
		const m = /^\s*(?:[A-Za-z_][A-Za-z0-9_]*=\S*\s+)*(?:rtk\s+)?git(?:\s+(.*))?$/.exec(segment);
		if (!m) continue;
		const tokens = (m[1] || '').trim().split(/\s+/).filter(Boolean);
		let dir = null;
		let i = 0;
		for (; i < tokens.length && tokens[i].startsWith('-'); i++) {
			if (tokens[i] === '-C') dir = tokens[i + 1] ? unquote(tokens[i + 1]) : null;
			if (GLOBAL_OPTS_WITH_VALUE.has(tokens[i])) i += 1;
		}
		out.push({ sub: tokens[i] || '', args: tokens.slice(i + 1), dir });
	}
	return out;
}

// 引用符付きで書かれることがある（git switch -c "feature/1-x"）。
function unquote(s) {
	return s.replace(/^['"]|['"]$/g, '');
}

// コマンドの中で作られるブランチの名前をすべて返す。
//
// 作成オプションの「次の、フラグでない語」を名前とみなす。オプションの並び順に
// 依存しないので、git switch -c <名前> でも git worktree add <パス> -b <名前> でも拾える。
function newBranchNames(command) {
	const names = [];
	for (const { sub, args } of gitInvocations(command)) {
		const flags = CREATE_FLAGS[sub];
		if (!flags) continue;
		for (let i = 0; i < args.length; i++) {
			const eq = /^(--create|--force-create)=(.+)$/.exec(args[i]);
			if (eq && flags.has(eq[1])) {
				names.push(unquote(eq[2]));
				break;
			}
			if (!flags.has(args[i])) continue;
			const name = args.slice(i + 1).find((t) => !t.startsWith('-'));
			if (name) names.push(unquote(name));
			break;
		}
	}
	return names;
}

// 品質チェックを1本走らせる。合格なら null、失敗ならユーザーに返す文言を返す。
function runCheck(repoRoot, check) {
	const abs = path.join(repoRoot, check.script);
	// 無ければ素通し。配布前のリポジトリや、checks を excludeShared で外した
	// リポジトリがあるため、存在しないこと自体は異常ではない。
	if (!fs.existsSync(abs)) return null;

	try {
		execFileSync('bash', [abs], {
			cwd: repoRoot,
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'pipe'],
			maxBuffer: 16 * 1024 * 1024,
			timeout: 15 * 60 * 1000,
		});
	} catch (e) {
		// 終了コードが取れない＝そもそも起動できなかった（bash が無い等）。
		// チェックの不備で全ての送信が止まるほうが被害が大きいので素通しする。
		if (e.status === undefined || e.status === null) return null;
		const combined = `${e.stdout || ''}${e.stderr || ''}`.trim();

		// 終了コード 3 は「環境の問題で実行できない」。品質上の指摘とは別物なので、
		// そうと分かる形で返す。ここを区別しないと、コンテナが起動していないだけの
		// ときに、AI が存在しない指摘を直そうとしてコードをいじり始める。
		if (e.status === EXIT_ENV_PROBLEM) {
			return (
				`${check.label}を実行できなかったため、送信をブロックしました。\n` +
				`**これは品質上の指摘ではなく、環境の問題です。コードを直しても解決しません。**\n\n` +
				`${combined}\n\n` +
				`対応:\n` +
				`1. 上記の案内に従って環境を整えてから、もう一度やり直してください\n` +
				`2. 環境を整えられない事情がある場合は、ユーザーに状況を説明して指示を仰いでください\n` +
				`   （許可を得たときだけ SKIP_QUALITY_CHECK=1 を先頭に付けられます）`
			);
		}

		return (
			`${check.label}に失敗したため、送信をブロックしました。\n\n` +
			`${combined}\n\n` +
			`対応:\n` +
			`1. 上記の指摘を修正し、コミットし直してからやり直してください\n` +
			`   （指摘が解消するまで、この手順を自分で繰り返してください）\n` +
			`2. 修正せずに進める必要がある場合は、必ずユーザーに確認し、\n` +
			`   許可を得たときだけ SKIP_QUALITY_CHECK=1 を先頭に付けてください\n` +
			`   （AI が自己判断でこの変数を付けることはルールで禁止しています）`
		);
	}
	return null;
}

/**
 * コマンドを評価して、実行を許すかどうかを返す。
 *
 * @param {{command?: string, cwd?: string}} input
 * @returns {{decision: 'allow'|'deny', reason?: string, note?: string}}
 */
function evaluate(input) {
	// 判定の前にコマンド行を整える。
	//   - 改行を \n にそろえる（CRLF のままだと、行末の \r のせいで git の呼び出しが見えなくなる）
	//   - ヒアドキュメントの本文を取り除く（実行されないデータなので）
	//   - 行末の \ でつないだ行を1行に戻す（`git switch \` と `-c 名前` を別々に読むと見落とす）
	const raw = ((input && input.command) || '').replace(/\r\n?/g, '\n');
	const command = stripHeredocs(raw).replace(/\\\n/g, ' ');
	if (!command) return allow();

	// 段階フィルタ。全てのシェル実行のたびに呼ばれるので、対象外だと分かった時点で
	// 最小コストで抜ける。大多数のコマンドはここで終わる。
	const mayCreate = command.includes('switch') || command.includes('checkout') || command.includes('worktree');
	const mayShip = command.includes('push') || command.includes('commit');
	if (!mayCreate && !mayShip) return allow();

	// --- ① ブランチ作成 -----------------------------------------------------

	if (mayCreate && !SKIP_BRANCH_RE.test(command)) {
		const branch = newBranchNames(command).find((name) => !BRANCH_RE.test(name));
		if (branch !== undefined) {
			return deny(
				`ブランチ名が規約に合っていないため、作成をブロックしました: ${branch}\n\n` +
					`  feature/<issue番号>-<内容を表す短い英語>\n` +
					`  fix/<issue番号>-<内容を表す短い英語>\n\n` +
					`このリポジトリは Issue 駆動です。**ブランチを切る前に Issue が要ります。**\n` +
					`Issue 番号が分からないということは、まだ Issue を作っていないということです。\n\n` +
					`正しい手順:\n` +
					`1. brainstorming で設計を詰める\n` +
					`2. writing-plans で実装計画を書く\n` +
					`3. creating-issues で計画を Issue に起こし、ユーザーの承認を得て作成する\n` +
					`4. その番号でブランチを切る（例: feature/42-add-csv-export）\n\n` +
					`creating-issues スキルが 3 と 4 の手順を持っています。\n` +
					`Issue を作らない一時的なブランチが本当に必要な場合は、ユーザーに確認し、\n` +
					`許可を得たときだけ SKIP_BRANCH_CHECK=1 を先頭に付けてください。`,
			);
		}
	}

	if (!mayShip) return allow();

	const isPush = GIT_PUSH_RE.test(command);
	const isCommit = GIT_COMMIT_RE.test(command);
	if (!isPush && !isCommit) return allow();

	// 判定するリポジトリは、その push / commit の呼び出しに付いた -C から取る。無ければ呼び出し元の cwd。
	// 最初の git の -C を取ると、`git -C A status && git -C B push` で A を判定してしまう。
	// 相対パスはコマンドの cwd を基準に解決する（guard のプロセスの cwd とは限らない）。
	const base = (input && input.cwd) || process.cwd();
	const ship = gitInvocations(command).find((inv) => inv.sub === 'push' || inv.sub === 'commit');
	const cwd = ship && ship.dir ? path.resolve(base, ship.dir) : base;

	let branch;
	let repoRoot;
	try {
		branch = git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd);
		repoRoot = git(['rev-parse', '--show-toplevel'], cwd);
	} catch {
		return allow(); // git リポジトリでない、または解決できない
	}

	// --- ② 保護ブランチ上での commit / push --------------------------------

	if (PROTECTED_BRANCHES.has(branch)) {
		const verb = isCommit && !isPush ? 'コミット' : '送信';
		return deny(
			`${branch} ブランチで直接${verb}しようとしています。\n\n` +
				`このリポジトリは Issue 駆動の開発フローを採っており、${branch} への直接の\n` +
				`変更は禁止されています（GitHub 側でも拒否されます）。\n\n` +
				`正しい手順:\n` +
				`1. Issue を起案してユーザーの承認を得る → creating-issues スキル\n` +
				`2. git switch ${branch} && git pull\n` +
				`3. git switch -c feature/<issue番号>-<内容>\n` +
				`4. 作業してコミットし、送信して gh pr create\n\n` +
				`creating-issues スキルがこの手順を持っています。`,
		);
	}

	// --- ③ 保護ブランチを指す refspec --------------------------------------

	if (isPush && pushTargetsProtected(command)) {
		return deny(
			`保護ブランチ（main / master）へ直接送信しようとしています。\n\n` +
				`変更は必ず PR 経由で入れてください。現在のブランチ ${branch} を送信し、\n` +
				`gh pr create で PR を作るのが正しい手順です。`,
		);
	}

	// --- ④ 品質チェック -----------------------------------------------------
	// ここから先は送信のときだけ。コミットは品質チェックの対象外。

	if (!isPush) return allow();

	if (SKIP_QUALITY_RE.test(command)) {
		// スキップした事実は必ず見える形にする。黙って素通しするとガードの意味が薄れる。
		return {
			decision: 'allow',
			note: 'SKIP_QUALITY_CHECK=1 の指定により、事前の品質チェックをスキップしました。',
		};
	}

	for (const check of CHECKS) {
		const failure = runCheck(repoRoot, check);
		if (failure) return deny(failure);
	}

	return allow();
}

module.exports = { evaluate };
