// generated by tk-media harness — DO NOT EDIT
// 変更したい場合はこのファイルを直接編集してよい（以後このファイルは上書きされません）
'use strict';

// Issue駆動フローの機械強制。判定ロジックの本体で、Claude Code / Cursor の
// どちらのアダプタからも同じ関数が呼ばれる。
//
// 止めるもの:
//   1. main / master 上での git commit・git push
//   2. refspec が main / master を指している git push
//   3. 品質チェックを通っていない git push
//
// 「機械判定できるものはドキュメントに書かない」の方針で、ルール文書に書いた
// フローのうち機械的に判定できる部分をここへ降ろしている。

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

// 保護対象ブランチ。ここへの直接の commit / push を止める。
const PROTECTED_BRANCHES = new Set(['main', 'master']);

// 品質チェックの2段構え。順序が意味を持つ（安いほうを先に置き、落ちたら次は走らせない）。
const CHECKS = [
	{ script: 'scripts/harness-check.sh', label: '共通チェック' },
	{ script: 'scripts/quality-check.sh', label: 'プロジェクト品質チェック' },
];

// チェックスクリプトの終了コード規約。1 は「品質上の指摘あり」、3 は「環境の問題で
// 実行できない」。後者は直すべき対象が違うので、返す文言を分けている。
const EXIT_ENV_PROBLEM = 3;

// コマンドラインのどこかにある git push / git commit を拾う。
// 素朴な部分一致だと echo で文字列を表示するだけの場合にも誤爆し、逆に
// git -C /path push のようなグローバルオプション付きの形を取りこぼす。以下の正規表現は:
//   - 行頭 or シェル区切り文字（; & | ( `）の直後に限定する
//   - 先頭に環境変数代入（例: FOO=bar git ...）が付いていても許容する
//   - git の直後に -C <path> のようなグローバルオプションが挟まってもよい
//   - 最後は push / commit という単語で終わる（pushurl 等への前方一致誤爆を避ける）
// 多少の過検知は許容する。過検知しても「チェックが通れば素通しする」だけで実害が無く、
// 逆に見逃しは仕組みの趣旨に反するため、迷ったら検知する側に倒す。
const GIT_PUSH_RE = /(^|[;&|(`])\s*([A-Za-z_][A-Za-z0-9_]*=\S*\s+)*git(\s+-\S+(\s+[^-\s]\S*)?)*\s+push(\s|$)/;
const GIT_COMMIT_RE = /(^|[;&|(`])\s*([A-Za-z_][A-Za-z0-9_]*=\S*\s+)*git(\s+-\S+(\s+[^-\s]\S*)?)*\s+commit(\s|$)/;

// git -C <dir> の <dir> を取り出す。無ければ呼び出し元の cwd で判定する。
const GIT_C_RE = /\bgit\s+(?:-\S+\s+)*?-C\s+(\S+)/;

// 誤検知やチェック自体の不具合で永久に push できなくなる事態を避けるための安全弁。
// ユーザーが明示的に許可した場合にのみ使う。AI が自己判断で付けることは
// ルール文書で禁止している（hook 側では「ユーザーの指示か AI の自己判断か」を
// 技術的に区別できないため、そこは文書規約に委ねる）。
const SKIP_RE = /(^|[;&|(`])\s*SKIP_QUALITY_CHECK=1\s/;

function allow() {
	return { decision: 'allow' };
}

function deny(reason) {
	return { decision: 'deny', reason };
}

function git(args, cwd) {
	return execFileSync('git', args, {
		cwd,
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'ignore'],
	}).trim();
}

// push 以降、次のシェル区切りまでの引数を見て、保護ブランチを指す refspec があるか調べる。
// feature/1-main-thing のような名前に誤爆しないよう、ref 全体との一致だけを見る。
function pushTargetsProtected(command) {
	const m = /\bpush\b([^;&|]*)/.exec(command);
	if (!m) return false;
	const args = m[1].trim();
	if (!args) return false;
	for (const token of args.split(/\s+/)) {
		if (token.startsWith('-')) continue;
		// <local>:<remote> の形なら、判定対象は送り先である右辺。
		const ref = token.includes(':') ? token.slice(token.indexOf(':') + 1) : token;
		if (PROTECTED_BRANCHES.has(ref)) return true;
	}
	return false;
}

// 品質チェックを1本走らせる。合格なら null、失敗ならユーザーに返す文言を返す。
function runCheck(repoRoot, check) {
	const abs = path.join(repoRoot, check.script);
	// 無ければ素通し。配布前のリポジトリや、checks を excludeShared で外した
	// リポジトリがあるため、存在しないこと自体は異常ではない。
	if (!fs.existsSync(abs)) return null;

	try {
		execFileSync('bash', [abs], {
			cwd: repoRoot,
			encoding: 'utf8',
			stdio: ['ignore', 'pipe', 'pipe'],
			maxBuffer: 16 * 1024 * 1024,
			timeout: 15 * 60 * 1000,
		});
	} catch (e) {
		// 終了コードが取れない＝そもそも起動できなかった（bash が無い等）。
		// チェックの不備で全ての送信が止まるほうが被害が大きいので素通しする。
		if (e.status === undefined || e.status === null) return null;
		const combined = `${e.stdout || ''}${e.stderr || ''}`.trim();

		// 終了コード 3 は「環境の問題で実行できない」。品質上の指摘とは別物なので、
		// そうと分かる形で返す。ここを区別しないと、コンテナが起動していないだけの
		// ときに、AI が存在しない指摘を直そうとしてコードをいじり始める。
		if (e.status === EXIT_ENV_PROBLEM) {
			return (
				`${check.label}を実行できなかったため、送信をブロックしました。\n` +
				`**これは品質上の指摘ではなく、環境の問題です。コードを直しても解決しません。**\n\n` +
				`${combined}\n\n` +
				`対応:\n` +
				`1. 上記の案内に従って環境を整えてから、もう一度やり直してください\n` +
				`2. 環境を整えられない事情がある場合は、ユーザーに状況を説明して指示を仰いでください\n` +
				`   （許可を得たときだけ SKIP_QUALITY_CHECK=1 を先頭に付けられます）`
			);
		}

		return (
			`${check.label}に失敗したため、送信をブロックしました。\n\n` +
			`${combined}\n\n` +
			`対応:\n` +
			`1. 上記の指摘を修正し、コミットし直してからやり直してください\n` +
			`   （指摘が解消するまで、この手順を自分で繰り返してください）\n` +
			`2. 修正せずに進める必要がある場合は、必ずユーザーに確認し、\n` +
			`   許可を得たときだけ SKIP_QUALITY_CHECK=1 を先頭に付けてください\n` +
			`   （AI が自己判断でこの変数を付けることはルールで禁止しています）`
		);
	}
	return null;
}

/**
 * コマンドを評価して、実行を許すかどうかを返す。
 *
 * @param {{command?: string, cwd?: string}} input
 * @returns {{decision: 'allow'|'deny', reason?: string, note?: string}}
 */
function evaluate(input) {
	const command = (input && input.command) || '';
	if (!command) return allow();

	// 段階フィルタ。全てのシェル実行のたびに呼ばれるので、対象外だと分かった時点で
	// 最小コストで抜ける。大多数のコマンドはここで終わる。
	if (!command.includes('push') && !command.includes('commit')) return allow();

	const isPush = GIT_PUSH_RE.test(command);
	const isCommit = GIT_COMMIT_RE.test(command);
	if (!isPush && !isCommit) return allow();

	const m = GIT_C_RE.exec(command);
	const cwd = m ? m[1] : (input && input.cwd) || process.cwd();

	let branch;
	let repoRoot;
	try {
		branch = git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd);
		repoRoot = git(['rev-parse', '--show-toplevel'], cwd);
	} catch {
		return allow(); // git リポジトリでない、または解決できない
	}

	if (PROTECTED_BRANCHES.has(branch)) {
		const verb = isCommit && !isPush ? 'コミット' : '送信';
		return deny(
			`${branch} ブランチで直接${verb}しようとしています。\n\n` +
				`このリポジトリは Issue 駆動の開発フローを採っており、${branch} への直接の\n` +
				`変更は禁止されています（GitHub 側でも拒否されます）。\n\n` +
				`正しい手順:\n` +
				`1. Issue を起案してユーザーの承認を得る → gh issue create\n` +
				`2. git switch ${branch} && git pull\n` +
				`3. git switch -c feature/<issue番号>-<内容>\n` +
				`4. 作業してコミットし、送信して gh pr create\n\n` +
				`start-issue-work スキルがこの手順を持っています。`,
		);
	}

	if (isPush && pushTargetsProtected(command)) {
		return deny(
			`保護ブランチ（main / master）へ直接送信しようとしています。\n\n` +
				`変更は必ず PR 経由で入れてください。現在のブランチ ${branch} を送信し、\n` +
				`gh pr create で PR を作るのが正しい手順です。`,
		);
	}

	// ここから先は送信のときだけ。コミットは品質チェックの対象外。
	if (!isPush) return allow();

	if (SKIP_RE.test(command)) {
		// スキップした事実は必ず見える形にする。黙って素通しするとガードの意味が薄れる。
		return {
			decision: 'allow',
			note: 'SKIP_QUALITY_CHECK=1 の指定により、事前の品質チェックをスキップしました。',
		};
	}

	for (const check of CHECKS) {
		const failure = runCheck(repoRoot, check);
		if (failure) return deny(failure);
	}

	return allow();
}

module.exports = { evaluate };
